name: Build Android APK

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0

      - name: Child App Build
        run: |
          cd flutter_child_app
          flutter clean
          flutter pub get
          flutter doctor -v
          flutter build apk --release -v

      - name: Parent App Build
        run: |
          cd flutter_parent_app
          flutter clean
          flutter pub get
          flutter build apk --release -v
